name: Nagios Nrpe Server
version: 2025.01.15-1
slug: nagios-nrpe
description: Nrpe with plugins 
url: https://github.com/DemoEffect/hassio-addon-nrpe
arch: 
  - amd64
  - aarch64
  - armv7
init: false
ports: 
  5666/tcp: 5666
ports_description: 
  5666/tcp: Default nrpe port
map: 
  - config:rw
startup: services
boot: auto
host_network: true
apparmor: true
#host_pid: true
#homeassistant: 2024.10.4
#advanced: true
#stage: experimental
#hassio_api: true
#homeassistant_api: true
#auth_api: true
#docker_api: true
options:
  allowed_hosts: "0.0.0.0/0"
schema:
  allowed_hosts: str?
